version: "3.8"
services:
  frontend:
    image: basic-img:latest
    ports:
      - "8081:80"
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    name: basic
    driver: bridge
                                                                                                                                                                                                              
