version: "3.8"
services:
  frontend:
    image: basic-img:latest
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    restart: always
    
networks:
  mynetwork:
    - name: basic
      driver: bridge